
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class SymbolTable {
  /* terminals */
  public static final int UNDERSCORE = 45;
  public static final int LT = 18;
  public static final int RECORD = 27;
  public static final int INTEGER_LITERAL = 5;
  public static final int MINUS = 12;
  public static final int INTERFACE = 48;
  public static final int OPEN_BRACE = 39;
  public static final int SEMICOLON = 43;
  public static final int EQB = 25;
  public static final int BREAK = 32;
  public static final int ELSE = 29;
  public static final int IF = 28;
  public static final int NULL = 10;
  public static final int CHARACTER_LITERAL = 4;
  public static final int MODULO = 16;
  public static final int TRUE = 6;
  public static final int HIGHTIMES = 14;
  public static final int NEQB = 26;
  public static final int NOT = 17;
  public static final int GEQ = 21;
  public static final int OPEN_PAREN = 37;
  public static final int AND = 22;
  public static final int PERIOD = 44;
  public static final int CLOSE_PAREN = 38;
  public static final int PROGRAM = 47;
  public static final int PLUS = 11;
  public static final int LENGTH = 34;
  public static final int CLOSE_BRACKET = 36;
  public static final int error = 1;
  public static final int INT = 8;
  public static final int DIVIDE = 15;
  public static final int RETURN = 31;
  public static final int CLOSE_BRACE = 40;
  public static final int IDENTIFIER = 2;
  public static final int EOF = 0;
  public static final int COMMA = 42;
  public static final int OR = 23;
  public static final int TIMES = 13;
  public static final int EQUALS = 24;
  public static final int USE = 33;
  public static final int OPEN_BRACKET = 35;
  public static final int COLON = 41;
  public static final int GT = 20;
  public static final int UMINUS = 46;
  public static final int BOOL = 9;
  public static final int LEQ = 19;
  public static final int STRING_LITERAL = 3;
  public static final int FALSE = 7;
  public static final int WHILE = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "STRING_LITERAL",
  "CHARACTER_LITERAL",
  "INTEGER_LITERAL",
  "TRUE",
  "FALSE",
  "INT",
  "BOOL",
  "NULL",
  "PLUS",
  "MINUS",
  "TIMES",
  "HIGHTIMES",
  "DIVIDE",
  "MODULO",
  "NOT",
  "LT",
  "LEQ",
  "GT",
  "GEQ",
  "AND",
  "OR",
  "EQUALS",
  "EQB",
  "NEQB",
  "RECORD",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "BREAK",
  "USE",
  "LENGTH",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "OPEN_BRACE",
  "CLOSE_BRACE",
  "COLON",
  "COMMA",
  "SEMICOLON",
  "PERIOD",
  "UNDERSCORE",
  "UMINUS",
  "PROGRAM",
  "INTERFACE"
  };
}

